FROM jupyter/scipy-notebook:latest

USER root

RUN deluser --remove-home $NB_USER

ENV HOME=/root
ENV XDG_CACHE_HOME=$HOME/.cache

RUN : \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get install libquadmath0 -y

RUN : \
    && pip3 install --upgrade pip \
    && pip3 install \
	torch \
	torchvision \
	catalyst \
	albumentations \
	opencv-python \
	efficientnet_pytorch \
	geffnet \
	tqdm \
	numpy \
	sklearn \
	scipy \
	matplotlib \
	pandas \
	onnx \
	tensorboard \
	pyyaml \
	scikit-learn \
	matplotlib \
	mxnet

RUN : \
    && apt-get clean \
    && apt-get autoclean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/* ~/.cache/* /tmp/* /var/tmp/*

EXPOSE 6006

WORKDIR /workdir

CMD ["/bin/bash", "-c", "jupyter lab --ip 0.0.0.0 --no-browser --allow-root"]
